### PR TITLE
Plugin not Wp 6.7/6.8 Compatible

### PR DESCRIPTION
**Pull request by BackuPs**
The plugin is not WP 6.7 / 6/8 Compatible because of updater.php is calling translation causing warnings and flooded error.logs

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the elementor-pro domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in /var/docs/public/wp-includes/functions.php on line 6115

Changing line 295 of the updater.php to 

		$data = get_plugin_data( $plugin_file, true, false );
		
Fixes the issue

### CODE REVIEW

**Comment by cetdelosaltos** [comment]
I tried the updater.php file update, and it fixed the alert, but the builder still doesn't run. I tried in a clean installation, only Elementor and ProElements with Hello Theme, and it just doesn't load the editor.

**Comment by BackuPs** [comment]
> I tried the updater.php file update, and it fixed the alert, but the builder still doesn't run. I tried in a clean installation, only Elementor and ProElements with Hello Theme, and it just doesn't load the editor.

What has this todo with my pull request? The fix i provided is for a warning message about loading translations too soon.


That elementor does not work on servers is in most cases (99.99%) because of  how your hoster has setup their server. And cheap hosters tend to cut down on memmory and available resources you need for elementor. It is what you get for a 5usd per month host.   

You can find more information at elementor.  https://elementor.com/help/requirements/

Please stick to the issue this pull request is about.

**Comment by cetdelosaltos** [comment]
How much disrespectful and discriminating assumption in one note... It's a 400$ a year VPS in GoDaddy I have maxed resources for this, and it just doesn't load.

**Comment by BackuPs** [comment]
> How much disrespectful and discriminating assumption in one note... It's a 400$ a year VPS in GoDaddy I have maxed resources for this, and it just doesn't load. Elementor loads if PRO Elements is not enabled

Firtst of all there is nothing discriminating about my reply nor is there a intention todo such.  I have been around in the hosting business for many years and one of the most common causes is cheap hosting and not having enough resources to run plugins.  I have been in many website also on GoDaddy (we call it different) to fix issues and it was always how they have setup their resources. 

You can turn on WP debug mode and see if and what error is causing it. But if you pay 400usd a year for hosting then they should help you with this.  

As for the issue here. Again this is not the place for you to report your problems with a free plugin that does not have active support as stated on https://proelements.org.  Also not this thread as it has a fix for a problem found which is not related to your issue.

You can and should seek help either from the elementor team (for which you need to buy elementor pro) or at your host (for which you already pay $400 a year as you say) to fix your issues.

**Comment by reteinformatica** [comment]
Hello everyone, on my site I get this error:

```
Warning: The _load_textdomain_just_in_time function was called incorrectly. The loading of the translation for the elementor-pro domain was activated too early. This is usually an indicator of plugin or theme code being run too early. Translations should be loaded at init action or later. For more information, see the WordPress Debug section. (This message was added in version 6.7.0.) in /home/todabei1/public_html/wp-includes/functions.php at line 6114

Warning: The Perflab_Server_Timing::send_header function was called incorrectly. The method must be called before the headers have been sent. For more information, see WordPress Debug. in /home/todabei1/public_html/wp-includes/functions.php at line 6114
```
I contacted the WordPress team who directed me to contact the creators of the plugins, pointing them to this link: https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/

**Comment by BackuPs** [comment]
> Hello everyone, on my site I get this error:
> 
> ```
> Warning: The _load_textdomain_just_in_time function was called incorrectly. The loading of the translation for the elementor-pro domain was activated too early. This is usually an indicator of plugin or theme code being run too early. Translations should be loaded at init action or later. For more information, see the WordPress Debug section. (This message was added in version 6.7.0.) in /xxx/xxx/public_html/wp-includes/functions.php at line 6114
> 
> Warning: The Perflab_Server_Timing::send_header function was called incorrectly. The method must be called before the headers have been sent. For more information, see WordPress Debug. in /xxx/xxx/public_html/wp-includes/functions.php at line 6114
> ```
> 
> I contacted the WordPress team who directed me to contact the creators of the plugins, pointing them to this link: https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/

The issue is fixed by this pull request.  Adjust the updater.php accordingly or download the pull request.

https://github.com/proelements/proelements/pull/27/files

You can only confirm here that it is fixed by the suggested change of the updater.php on line 295.

You can adjust the file by using ftp and a text editor like notepad++  or download the changed master from my repository.    https://github.com/BackuPs/proelements/tree/master

**Comment by reteinformatica** [comment]
Thank you BackuPs, problem solved.

**Comment by BackuPs** [comment]
> Thank you very much @BackuPs

You are welcome.  I hope the pro elements developer picks up this  change as i do not want to have to change the  updater.php file on every update,

**Comment by BackuPs** [comment]
Apparently the pro elements developer does not test with wp 6.7 6.8 and debug mode on as the issue still exists in the latest 3.25.5 version in his updater.php  

So one still has to change line 295 in the update.php to

		$data = get_plugin_data( $plugin_file, true, false );
		
in order to suppress warning message about Function _load_textdomain_just_in_time was called incorrectly. 

Sorry about that.

**Pull request closed without merging**
